### ISSUE TITLE
How to build one of these Vue projects?

### ISSUE THREAD

**Issue by janetZhangHK01** [more-ginger/scrollytelling-beginners#2]
Thank you so much for these high quality tutorial.

Would you please teach me how to build one of these Vue projects? Say, "S03-Task-5".
I tried 'npm run build', but no folder named 'dist' generated.

It seems these projects no need to build, I can simply open the index.html.

**Comment by more-ginger** [comment]
Hi!
Thanks for enjoying the tutorials and sorry for the late reply :)

As you said, in our case you won't need to build the folder, because the structure is the classic html + css + js. 
We are using npm only to launch a local server, ideally once your project is ready to go online you can use FileZilla or similar FTP  clients to directly upload files.

Hope it helps!

**Comment by janetZhangHK01** [comment]
Hi !

It's great to hear from you.

Yes, for a time I wondered if no need npm to build this project, what's the
purpose of using it. After trial and I guess it's for launch a local
server.

Thank you again for your previous time and your instructive explain!


Best regards,

張思偉 Janet Zhang
數據新聞產品開發專員 News Room Developer

E/ janetzhang@hk01.com
M/ 852 5372 2819
W/ www.hk01.com

[image: HK01] <http://www.hk01.com/>
香港01有限公司 HK01 Company Limited
香港荃灣沙咀道6號嘉達環球中心11樓
11/F, The Octagon, No. 6 Sha Tsui Road, Tsuen Wan, N.T. HK

[image: HK01-ANDROID]
<https://play.google.com/store/apps/details?id=com.hk01.news_app> [image:
HK01-IOS] <https://appsto.re/hk/2dQPab.i>


fmorini <notifications@github.com> 於 2020年8月18日 週二 上午1:06寫道：
